---
framework: jest
preRun:
     command:
        - npm install
preMerge:
  pattern:
    - "./tests/*.spec.ts"
postMerge:
  pattern:
    - "./tests/*.spec.ts"
postRun:
     command:
        - node --version
configFile: jest.config.js
version: 1.0

